### ISSUE TITLE
Hours not displayed

### ISSUE THREAD

**Issue by oceanlazy** [Skucul/timepicker#1]
After `python timepicker.py`
[screenshot](https://imgur.com/a/roAxbLj)
```
[INFO   ] [Logger      ] Record log in /home/v/.kivy/logs/kivy_19-01-31_55.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 18.0.5'>
[INFO   ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'SVGA3D; build: RELEASE;  LLVM;'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range

```

**Comment by caver456** [comment]
same here.  Kivy 1.10.1 on Windows 10.  Using timepicker in this manner in the application's .kv file:

```
#:import Window kivy.core.window.Window
#:import DatePicker datepicker
#:import TimePicker timepicker
...
...
        BoxLayout:
            size_hint_y: None
            height: 40
            Label:
                text: 'Event/O.P. Start Date:'
            DatePicker:
                id: eventStartDate
            Label:
                text: 'Start Time:'
            TimePicker:
                id: eventStartTime
```

Planning to dive in to the debug now.  @vadimk2016 did you find a solution?

**Comment by caver456** [comment]
the actual error is that line 127 in _text_sdl2.pyx (compiled after installed, but the source is on github) expects a four-element list (r,g,b,a) for options['color'], but, it's only a three-element list for the hour and minute numbers around the circle.  It's a valid four-element list for the hh:mm AM/PM displays.  Now to track down how to change that in the timepicker code...

**Comment by caver456** [comment]
this ugly brute force solution works but is probably not the right way to do it; I'll use it in my app and see if anything else goes wrong.

In _genitems, line 259, where it sets the color of the Number object as the last argument, change it from color=self.color to color=self.color+[1]:

`            n = Number(text=self.number_format_string.format(i), size_factor=self.number_size_factor, color=self.color+[1])`

looks like this repo may not get any attention, but, even if it did this brute force solution is not really ready for a pull request anyway.
