### ISSUE TITLE
crash when rotating minutes clockwise past 59

### ISSUE THREAD

**Issue by caver456** [Skucul/timepicker#2]
kivy 1.10.1
Windows 10
Python 3.7.0

```
[INFO   ] [Base        ] Start application main loop
[INFO   ] [on_text called]<__main__.ComboEdit object at 0x0948D420>:
[INFO   ] [on_options called]<__main__.ComboEdit object at 0x0948D420>:[]
[INFO   ] [options     ][]
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 1101, in <module>
     theApp.run()
   File "C:\Python37-32\lib\site-packages\kivy\app.py", line 826, in run
     runTouchApp()
   File "C:\Python37-32\lib\site-packages\kivy\base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Python37-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "C:\Python37-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "C:\Python37-32\lib\site-packages\kivy\base.py", line 340, in idle
     self.dispatch_input()
   File "C:\Python37-32\lib\site-packages\kivy\base.py", line 325, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Python37-32\lib\site-packages\kivy\base.py", line 284, in post_dispatch_input
     wid.dispatch('on_touch_move', me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\caver\Documents\GitHub\sign-in\timepicker.py", line 275, in on_touch_move
     self.selected = self.number_at_pos(*touch.pos)
   File "kivy\properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 524, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "C:\Users\caver\Documents\GitHub\sign-in\timepicker.py", line 555, in on_selected
     self.minutes = self._picker.selected
   File "kivy\properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 524, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1296, in kivy.properties.ReferenceListProperty.trigger_change
   File "kivy\properties.pyx", line 1311, in kivy.properties.ReferenceListProperty.trigger_change
   File "kivy\properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1449, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1452, in kivy.properties.AliasProperty.trigger_change
   File "C:\Users\caver\Documents\GitHub\sign-in\timepicker.py", line 489, in _get_time
     return datetime.time(*self.time_list)
 ValueError: minute must be in 0..59
```

**Comment by caver456** [comment]
self.time_list is a two-element list [hours,minutes] - timepicker thinks that 60 is after 59, but datetime.time barfs on this - it needs 0 to 59.  So, here's a preliminary brute-force fix: modify _get_time (line 485) to set time_list[1] to 0 if it was 60:

```
    def _get_time(self):
        if self.time_list[1]==60:
            self.time_list[1]=0
#         print("_get_time called: time_list="+str(self.time_list))
        return datetime.time(*self.time_list)
```
